# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGSOfHLg_sekWufV8n0fa-JZ6voB4CkA
"""

# Step 1: Install Necessary Libraries
# You can install the required libraries using pip if you don't have them installed already.
# pip install scikit-learn

# Step 2: Import Required Libraries
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

# Step 3: Load the Iris Dataset
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Labels

# Step 4: Split the Dataset
# Split the data into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Print the Number of Samples in Training and Testing Sets
print("Number of samples in the training set:", len(X_train))
print("Number of samples in the testing set:", len(X_test))