# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGSOfHLg_sekWufV8n0fa-JZ6voB4CkA
"""

# Step 1: Install Necessary Libraries
# Run in your terminal or command prompt: pip install numpy pandas scikit-learn

# Step 2: Import the Required Libraries
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

# Step 3: Load the Iris Dataset
# The load_iris function loads the dataset into a Bunch object, similar to a dictionary.
iris = load_iris()

# Step 4: Convert the Dataset to a DataFrame
# Convert the dataset into a pandas DataFrame for easier data manipulation and analysis.
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

# Step 5: Display the First Five Rows of the Dataset
# Use the head() function to display the first five rows, providing a quick view of the data.
print("First five rows of the dataset:")
print(df.head())

# Step 6: Display the Shape of the Dataset
# The shape attribute returns the number of rows and columns in the dataset.
print("\nShape of the dataset (rows, columns):")
print(df.shape)

# Step 7: Calculate and Display Summary Statistics
# The describe() function provides summary statistics including mean, std, min, and max for each feature.
print("\nSummary statistics for each feature:")
print(df.describe())